name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Whenever I visit the user account page (1-2 times a week)"
    validations:
      required: true
  - type: textarea
    id: preconditions
    attributes:
      label: "Preconditions"
      description: How do you set up the necessary environment or conditions for triggering this bug? Please detail any prerequisites or initial state required.
      value: "* User is logged in"
  - type: textarea
    id: reproduce-steps
    attributes:
      label: "Steps To Reproduce"
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
  - type: textarea
    id: actual-result
    attributes:
      label: "Actual Result"
      description: What is the unexpected outcome or behavior observed when reproducing the bug? 
  - type: textarea
    id: expected-result
    attributes:
      label: "Expected Result"
      description: What is the expected outcome or behavior when triggering the bug? 
  - type: textarea
    id: attachments
    attributes:
      label: "Attachments"
      description: Attach any relevant files or screenshots related to the bug, if available.
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Attach any relevant log files or error messages that may be helpful for debugging the bug, if available.
