name: Feature Request
description: Feature Request Template
title: "[Feature]: "
labels: ["bug", "triage"]
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: "What's wrong?"
