name: Feature Request
description: Feature Request Template
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Please describe your feature request in detail."
  - type: textarea
    attributes:
      label: "Feature Request"
